// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProject10;

internal sealed partial class Vsix
{
    public const string Id = "VSIXProject10.6c48a87a-214a-4815-b966-102603d78c1d";
    public const string Name = "VSIXProject10";
    public const string Description = @"Empty VSIX Project.";
    public const string Language = "en-US";
    public const string Version = "1.0";
    public const string Author = "Tim Heuer";
    public const string Tags = "";
}
