// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProject10;

using System;

/// <summary>
/// Helper class that exposes all GUIDs used across VS Package.
/// </summary>
internal sealed partial class PackageGuids
{
    public const string VSIXProject10String = "54e92e56-7e33-4698-9868-226e93c83bc5";
    public static Guid VSIXProject10 = new Guid(VSIXProject10String);
}
/// <summary>
/// Helper class that encapsulates all CommandIDs uses across VS Package.
/// </summary>
internal sealed partial class PackageIds
{
    public const int MyMenuGroup = 0x0001;
    public const int MyCommand = 0x0100;
}